#########################################################
# Busca actualizaciones y devuelve la lista (si las hay).
#########################################################
tasks:
  - name: Busca actualizaciones y devuelve la lista (si las hay).
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: searched
    register: list_of_found_updates
  - debug:
      var: list_of_found_updates